<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CopilotDemo.Domain\CopilotDemo.Domain.csproj" />
    <ProjectReference Include="..\CopilotDemo.Infrastructure\CopilotDemo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
